import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PrelineScript from "@/components/PrelineScript";
import { ThemeProvider } from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider disableTransitionOnChange>
          <Navbar />
          <div className="h-auto w-full dark:bg-black bg-white  dark:bg-dot-white/[0.16] bg-dot-black/[0.16] relative flex items-center justify-center">
            {/* Radial gradient for the container to give a faded look */}
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
      <PrelineScript />
    </html>
  );
}
